[input]
type="dir"
path = "/vast/projects/RCP/benchmarking/DiaNN/P4025/*.d"
ext="*.d"
[[extra]]
name="fasta"
path="/vast/projects/RCP/benchmarking/DiaNN/P4025/Human_Proteome_reviewed_May2021.fasta"
[[extra]]
name="tsv"
path="/vast/projects/RCP/benchmarking/DiaNN/P4025/library.tsv"

[output]
path = "/vast/scratch/users/iskander.j/test" 

[jobs]
num_reps = 1 
params_path = "/vast/scratch/users/iskander.j/ToolParametriser/examples/DiaNNbenchmarking-profiles.csv" 
tool_type="DiaNN"
run_type="lib"
email=""
qos="normal"